### ISSUE TITLE
Memory errors - uses_ vs cse_base

### ISSUE THREAD

**Issue by socumbersome** [AnyDSL/henk#10]
On test7 valgrind shows memory errors -- seems like we need to look at `uses_` set and carefully state what it keeps and why, because it may happen, that some duplicated expressions is deleted in `cse_base` while some use of this just deleted expression is floating around!

**Comment by leissa** [comment]
Also running all tests after another causes memory bugs, we should check that together... as soon as the electricity is back in university... :)
